# Simulador aMORA - Docker Compose Corrigido
# ==========================================

version: '3.8'

services:
  # API Backend
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: simulador-amora-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - simulador-network

  # Frontend Simples (servir arquivos)
  frontend:
    image: python:3.11-slim
    container_name: simulador-amora-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    working_dir: /app
    command: ["python", "-m", "http.server", "3000"]
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - simulador-network

networks:
  simulador-network:
    driver: bridge